### ISSUE TITLE
Uncaught TypeError: Cannot read property 'include' of undefined     at l.ellipse.js:18

### ISSUE THREAD

**Issue by eebasadre20** [jdfergason/Leaflet.Ellipse#8]
When I tried to used this library I keep getting this error  `Uncaught TypeError: Cannot read property 'include' of undefined  at l.ellipse.js:18`, any idea about this?

**Comment by ericsvendsen** [comment]
You probably need to either upgrade your leaflet dependency to at least 1.0, or use an [older version of l.ellipse.js](https://github.com/jdfergason/Leaflet.Ellipse/blob/85935a3c1c0f776478e38a99935876eaaf32506f/l.ellipse.js)

**Comment by jdfergason** [comment]
Your version of leaflet is too old, you need leaflet 1.0+
