### ISSUE TITLE
Is there any way to set the fill color of the ellipse?

### ISSUE THREAD

**Issue by shafiquejamal** [jdfergason/Leaflet.Ellipse#9]
The default is blue. How would I set it to red or some other color? 

Many thanks for this great work!

**Comment by jdfergason** [comment]
Styling is done the same way other primitives are styled in leaflet:

```js
// green ellipse
var ellipse1 = L.ellipse([51.505, -0.05], [500, 200], 0, {
        color: 'green', 
        fillColor: 'green',
        fillOpacity: 0.5
}).addTo(map);
```

See the demo for a working example: http://jdfergason.github.io/Leaflet.Ellipse/
